### ISSUE TITLE
Issue when try to acquire multiple drives

### ISSUE THREAD

**Issue by samicheema** [libyal/libewf#136]
Hi I am trying to acquire multiple drives using customized [ewfacquire.c](https://github.com/libyal/libewf/blob/master/ewftools/ewfacquire.c). But my application got stuck when call it for the second drive. It works absolutely fine for the single drive. Could you please suggest something which can help me escalating this problem.

Thanks in advance.

Regards,
Sami Cheema

**Comment by joachimmetz** [comment]
Which version of libewf are you using?

**Comment by samicheema** [comment]
@joachimmetz, thanks this issue was fixed. Now I am facing another issue, Its not acquiring C:\ drive all else are working fine in case of logical drives acquisitions.

**Comment by joachimmetz** [comment]
@samicheema I'm still not sure what the issue was but I'll close it out.
